package com.ayrotek.forum.dto;

import com.ayrotek.forum.entity.Thread;
import com.ayrotek.forum.entity.SubThread;
import com.ayrotek.forum.entity.Message;
import com.ayrotek.forum.entity.MessageVote;
import com.ayrotek.forum.dto.ThreadDto;
import com.ayrotek.forum.dto.SubThreadDto;
import com.ayrotek.forum.dto.MessageDto;
import com.ayrotek.forum.dto.MessageVoteDto;
import java.util.List;
import java.util.stream.Collectors;

public class DtoMapper {
    // Thread
    public static ThreadDto toDto(Thread thread) {
        if (thread == null) return null;
        ThreadDto dto = new ThreadDto();
        dto.setId(thread.getId());
        dto.setUsername(thread.getUserId());
        dto.setVehicleType(thread.getRole()); // VehicleType is 'role' in entity
        dto.setModelId(thread.getModelId());
        dto.setTitle(thread.getTitle());
        dto.setCreatedAt(thread.getCreatedAt());
        return dto;
    }
    public static Thread toEntity(ThreadDto dto) {
    if (dto == null) return null;
    Thread thread = new Thread();
    // Do not set ID or createdAt from DTO; these are generated by the database
    thread.setUserId(dto.getUsername());
    thread.setRole(dto.getVehicleType()); // VehicleType is 'role' in entity
    thread.setModelId(dto.getModelId());
    thread.setTitle(dto.getTitle());
    return thread;
    }
    // SubThread
    public static SubThreadDto toDto(SubThread subThread) {
        if (subThread == null) return null;
        SubThreadDto dto = new SubThreadDto();
        dto.setId(subThread.getId());
        if (subThread.getThread() != null) {
            dto.setThreadId(subThread.getThread().getId());
        }
        if (subThread.getUserId() != null) {
            dto.setUsername(subThread.getUserId());
        }
        dto.setTitle(subThread.getTitle());
        dto.setCreatedAt(subThread.getCreatedAt());
        return dto;
    }
    
    // For toEntity, you must set Thread externally (service/controller)
    public static SubThread toEntity(SubThreadDto dto, Thread thread) {
        if (dto == null) return null;
        SubThread subThread = new SubThread();
        // Do not set ID or createdAt from DTO; these are generated by the database
        subThread.setThread(thread);
        if (dto.getUsername() != null) {
            subThread.setUserId(dto.getUsername());
        }
        subThread.setTitle(dto.getTitle());
        return subThread;
    }
    // Message
    public static MessageDto toDto(Message message) {
        if (message == null) return null;
        MessageDto dto = new MessageDto();
        dto.setId(message.getId());
        dto.setBody(message.getBody());
        if (message.getUserId() != null) {
            dto.setUsername(message.getUserId());
        }
        if (message.getSubThread() != null) {
            dto.setSubThreadId(message.getSubThread().getId());
        }
        return dto;
    }
    
    // For toEntity, you must set SubThread externally (service/controller)
    public static Message toEntity(MessageDto dto, SubThread subThread) {
        if (dto == null) return null;
        Message message = new Message();
        // Do not set ID or createdAt from DTO; these are generated by the database
        message.setBody(dto.getBody());
        if (dto.getUsername() != null) {
            message.setUserId(dto.getUsername());
        }
        message.setSubThread(subThread);
        return message;
    }
    // MessageVote
    public static MessageVoteDto toDto(MessageVote vote) {
        if (vote == null) return null;
        MessageVoteDto dto = new MessageVoteDto();
        dto.setMessageId(vote.getMessageId());
        if (vote.getUserId() != null) {
            dto.setUsername(vote.getUserId());
        }
        dto.setUpvoted(vote.isUpvoted());
        dto.setCreatedAt(vote.getCreatedAt());
        dto.setUpdatedAt(vote.getUpdatedAt());
        return dto;
    }
    
    public static MessageVote toEntity(MessageVoteDto dto) {
        if (dto == null) return null;
        MessageVote vote = new MessageVote();
        vote.setMessageId(dto.getMessageId());
        if (dto.getUsername() != null) {
            vote.setUserId(dto.getUsername());
        }
        vote.setUpvoted(dto.isUpvoted());
        vote.setUpdatedAt(dto.getUpdatedAt());
        // Do not set createdAt from DTO; generated by the database
        return vote;
    }
    // List mappers
    public static List<ThreadDto> toThreadDtoList(List<Thread> threads) {
        return threads.stream().map(DtoMapper::toDto).collect(Collectors.toList());
    }
    public static List<SubThreadDto> toSubThreadDtoList(List<SubThread> subThreads) {
        return subThreads.stream().map(DtoMapper::toDto).collect(Collectors.toList());
    }
    public static List<MessageDto> toMessageDtoList(List<Message> messages) {
        return messages.stream().map(DtoMapper::toDto).collect(Collectors.toList());
    }
    public static List<MessageVoteDto> toMessageVoteDtoList(List<MessageVote> votes) {
        return votes.stream().map(DtoMapper::toDto).collect(Collectors.toList());
    }
}
