services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=forumdb'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
