server:
  port: 8080

spring:
  application:
    name: forum-service

  datasource:
    url: jdbc:postgresql://localhost:5432/forumdb
    username: myuser
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: never

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info
